events {
    worker_connections 1024;
}

http {
    
    upstream websocket_backend {
        # ip_hash гарантирует, что один и тот же клиент будет попадать на один и тот же сервер
        # Это полезно, если мы не используем Redis для сессий, но в нашей архитектуре
        # Dynamic Binding в RabbitMQ позволяет не использовать ip_hash, так как
        # сообщения маршрутизируются через RabbitMQ.
        # Однако для WebSockets это часто полезно для стабильности.
        # ip_hash; 
        
        server ws-service-1:8000;
        server ws-service-2:8000;
        server ws-service-3:8000;
    }

    upstream api_backend {
        
        server api-service-1:8000;
        server api-service-2:8000;
        server api-service-3:8000;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://api_backend;
            
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        }

        location /ws {
            proxy_pass http://websocket_backend;
            
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            
            proxy_read_timeout 86400s;
            proxy_send_timeout 86400s;
        }
    }
}